### ISSUE TITLE
Google Drive's link broken

### ISSUE THREAD

**Issue by BirkhoffG** [divyat09/cf-feasibility#2]
I want to try the dummy dataset (Simple-BN) in your [paper](https://arxiv.org/pdf/1912.03277.pdf). However, the dataset's link to Google Drive is broken. It says that the data is in owner's trash. Can you please provide new links containing the dataset?

Thanks.

**Comment by divyat09** [comment]
Thanks for pointing this out,  I have updated the link and it should work fine now. Also, you can generate the Simple-BN dataset easily using the file: 'generativecf/scripts/simple-bn-gen.py'.
